tools:
  - name: samtools-merge
    path: samtools-merge
    versions:
      - name: 1.12.0
        path: 1.12.0/samtools-merge__1.12.0.cwl
        md5sum: c45cb7a5439a5c1e438f8d81ec042939
    categories:
      - bam handlers
  - name: tabix
    path: tabix
    versions:
      - name: 0.2.6
        path: 0.2.6/tabix__0.2.6.cwl
        md5sum: bc2a1c49f74935479d75b7a85a0ec1ef
    categories: []
  - name: sambamba-merge-and-index
    path: sambamba-merge-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-merge-and-index__0.8.0.cwl
        md5sum: 1cdd2a6daff8b7fb232d08b915293d79
    categories: []
  - name: sambamba-sort-and-index
    path: sambamba-sort-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-sort-and-index__0.8.0.cwl
        md5sum: 1a6a0ac845bfffcfb32242f7388315be
    categories:
      - bam handler
  - name: sambamba-slice-and-index
    path: sambamba-slice-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-slice-and-index__0.8.0.cwl
        md5sum: 85cb186f34a4c635c6a3ed9f5e1dc701
    categories:
      - bam handler
  - name: sambamba-view-and-index
    path: sambamba-view-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-view-and-index__0.8.0.cwl
        md5sum: 5e4f3c81211efefcf6bc23fb59bb2ab1
    categories:
      - bam handler
  - name: optitype
    path: optitype
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype__1.3.5.cwl
        md5sum: c48f5ee0ce0017eaeb12f2d1f0de1c62
    categories:
      - hla
  - name: custom-subset-bam
    path: custom-subset-bam
    versions:
      - name: 1.12.0
        path: 1.12.0/custom-subset-bam__1.12.0.cwl
        md5sum: beccb4a5e29eed5de0be6dc7617f3602
    categories:
      - bam handler
  - name: custom-hla-bed-from-faidx
    path: custom-hla-bed-from-faidx
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-hla-bed-from-faidx__1.0.0.cwl
        md5sum: 34b3939fbdb3d642e299b3662151d284
    categories: []
  - name: bedops
    path: bedops
    versions:
      - name: 2.4.39
        path: 2.4.39/bedops__2.4.39.cwl
        md5sum: 94cac9220b0156075600bc0a26a0c4b9
    categories: []
  - name: dragen-germline
    path: dragen-germline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline__3.7.5.cwl
        md5sum: 54dd1c2214ab62a252ba9fb195af749d
      - name: 3.9.3
        path: 3.9.3/dragen-germline__3.9.3.cwl
        md5sum: f36d87507aec49bc61478a40adc2f283
    categories: []
  - name: custom-create-tso500-samplesheet
    path: custom-create-tso500-samplesheet
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-create-tso500-samplesheet__1.0.0.cwl
        md5sum: 29de97b423f0c16bc3b0200e4449a51f
    categories:
      - tso500
  - name: tso500-ctdna-demultiplex-workflow
    path: tso500-ctdna-demultiplex-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-demultiplex-workflow__1.1.0--120.cwl
        md5sum: 13ed54cdb34d2d8647689167ecbf8178
    categories:
      - tso500
  - name: tso500-ctdna-analysis-workflow
    path: tso500-ctdna-analysis-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-analysis-workflow__1.1.0--120.cwl
        md5sum: 131f6bd5a7772fd52d1f3b484c814820
    categories:
      - tso500
  - name: tso500-ctdna-reporting-workflow
    path: tso500-ctdna-reporting-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-reporting-workflow__1.1.0--120.cwl
        md5sum: c7080574aeb6c445d26f1dd2045a93d4
    categories:
      - tso500
  - name: custom-samplesheet-split-by-settings
    path: custom-samplesheet-split-by-settings
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-samplesheet-split-by-settings__1.0.0.cwl
        md5sum: 4dd3425af669e23740532a838748f9d8
    categories: []
  - name: bclConvert
    path: bclConvert
    versions:
      - name: 3.7.5
        path: 3.7.5/bclConvert__3.7.5.cwl
        md5sum: 974f3efc9ceb0134dc8e6a3177bc2e6d
    categories: []
  - name: create-dummy-file
    path: create-dummy-file
    versions:
      - name: 1.0.0
        path: 1.0.0/create-dummy-file__1.0.0.cwl
        md5sum: e3489c0a1a03c088ce4b0865105b348d
    categories: []
  - name: multiqc-interop
    path: multiqc-interop
    versions:
      - name: 1.2.1
        path: 1.2.1/multiqc-interop__1.2.1.cwl
        md5sum: 346fde115ccefa53c32b28be0c9978ff
    categories: []
  - name: dragen-somatic
    path: dragen-somatic
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic__3.7.5.cwl
        md5sum: 2bcb01913c07577e2674cc5a5553af86
      - name: 3.9.3
        path: 3.9.3/dragen-somatic__3.9.3.cwl
        md5sum: b59c904caa3eca256a3e4f50a4e734bc
    categories: []
  - name: dragen-transcriptome
    path: dragen-transcriptome
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-transcriptome__3.7.5.cwl
        md5sum: 8eca9ab4d832b874eec8ed03284e6c06
      - name: 3.8.4
        path: 3.8.4/dragen-transcriptome__3.8.4.cwl
        md5sum: 1164dc07f35924f483f17790b0e7aaf0
      - name: 3.9.3
        path: 3.9.3/dragen-transcriptome__3.9.3.cwl
        md5sum: d0398bddeb3b145fbd7f67ba9542f762
    categories: []
  - name: arriba-fusion-calling
    path: arriba-fusion-calling
    versions:
      - name: 2.0.0
        path: 2.0.0/arriba-fusion-calling__2.0.0.cwl
        md5sum: 69aa192fdf98f2ad3356e37a3fda5519
    categories: []
  - name: arriba-drawing
    path: arriba-drawing
    versions:
      - name: 2.0.0
        path: 2.0.0/arriba-drawing__2.0.0.cwl
        md5sum: 87ee5552c7c0e3aad1a74d5b3a75dc4b
    categories: []
  - name: multiqc
    path: multiqc
    versions:
      - name: 1.10.1
        path: 1.10.1/multiqc__1.10.1.cwl
        md5sum: 41ed548ff78108ac73741fd6cdc6ea6c
      - name: 1.11.0
        path: 1.11.0/multiqc__1.11.0.cwl
        md5sum: 59614d4be56c46d9ac9d31bcef91eff8
    categories:
      - qc
      - visual
  - name: dragen-alignment
    path: dragen-alignment
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-alignment__3.7.5.cwl
        md5sum: b6b90c6e5016c4718c73813b10699a32
      - name: 3.9.3
        path: 3.9.3/dragen-alignment__3.9.3.cwl
        md5sum: 84d0540ee7938589d9b0fda55b087a97
    categories: []
  - name: custom-create-directory
    path: custom-create-directory
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-create-directory__1.0.0.cwl
        md5sum: 64731e790930737d925417c6166fa43a
      - name: 2.0.0
        path: 2.0.0/custom-create-directory__2.0.0.cwl
        md5sum: 52557029b02ff7f5df78427603435985
    categories: []
  - name: dragen-build-reference-tarball
    path: dragen-build-reference-tarball
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-build-reference-tarball__3.7.5.cwl
        md5sum: 6125bf3e82c9bc95b6cee76a7cb11b27
      - name: 3.8.4
        path: 3.8.4/dragen-build-reference-tarball__3.8.4.cwl
        md5sum: f446aa06c779ae43e519c3b00d33f5fb
    categories: []
  - name: bgzip
    path: bgzip
    versions:
      - name: 1.12.0
        path: 1.12.0/bgzip__1.12.0.cwl
        md5sum: a941c2a36bcf67845e567cc819d4540c
    categories: []
  - name: mosdepth
    path: mosdepth
    versions:
      - name: 0.3.1
        path: 0.3.1/mosdepth__0.3.1.cwl
        md5sum: e436b2ed4f540260fbe23d9083d4f9d4
    categories: []
  - name: custom-tso500-make-region-coverage-qc
    path: custom-tso500-make-region-coverage-qc
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-tso500-make-region-coverage-qc__1.0.0.cwl
        md5sum: 5e19ae611db0596ff29c5800fbed983a
    categories: []
  - name: custom-tso500-make-exon-coverage-qc
    path: custom-tso500-make-exon-coverage-qc
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-tso500-make-exon-coverage-qc__1.0.0.cwl
        md5sum: 3949f76247815d897622d7f6c46ec23d
    categories: []
  - name: custom-tso500-align-collapse-fusion-caller-csv-metrics-to-json
    path: custom-tso500-align-collapse-fusion-caller-csv-metrics-to-json
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-tso500-align-collapse-fusion-caller-csv-metrics-to-json__1.0.0.cwl
        md5sum: 2af72e084bbe136f95168107828cfe85
    categories: []
  - name: custom-tsv-to-json
    path: custom-tsv-to-json
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-tsv-to-json__1.0.0.cwl
        md5sum: c0148d43a45228d210b88681a9563ff6
    categories: []
  - name: custom-tar-vcf-file-list
    path: custom-tar-vcf-file-list
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-tar-vcf-file-list__1.0.0.cwl
        md5sum: f10fea13b4459d8da5da415499771220
    categories: []
  - name: custom-gzip-file
    path: custom-gzip-file
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-gzip-file__1.0.0.cwl
        md5sum: f3152ef798d1afbeb2cdb652a8d8b9f8
    categories: []
  - name: custom-tar-file-list
    path: custom-tar-file-list
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-tar-file-list__1.0.0.cwl
        md5sum: 5ef823e36fdca3e099facc3a7f91fb17
    categories: []
  - name: custom-create-umccrise-tsv
    path: custom-create-umccrise-tsv
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/custom-create-umccrise-tsv__1.2.1--0.cwl
        md5sum: a9a20811b5ea3450aa0e97c25d9a3f1a
      - name: 1.2.2--0
        path: 1.2.2--0/custom-create-umccrise-tsv__1.2.2--0.cwl
        md5sum: 27ef6b74ebe003afbe5693e87a44d63d
    categories: []
  - name: umccrise
    path: umccrise
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/umccrise__1.2.1--0.cwl
        md5sum: 728444df3f171fcd9e177820e1e4ca9b
      - name: 1.2.2--0
        path: 1.2.2--0/umccrise__1.2.2--0.cwl
        md5sum: b45335f64405758c5c16651ee583e1e9
    categories: []
  - name: custom-create-umccr-dragen-refdata-tarball-from-illumina-tar
    path: custom-create-umccr-dragen-refdata-tarball-from-illumina-tar
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-create-umccr-dragen-refdata-tarball-from-illumina-tar__1.0.0.cwl
        md5sum: 8257c838637a3ddc40e0a7ddb2853727
    categories: []
  - name: dragen-umi
    path: dragen-umi
    versions:
      - name: 3.8.4
        path: 3.8.4/dragen-umi__3.8.4.cwl
        md5sum: 90c35e4db6a2e3202bd628049dd19c31
      - name: 3.9.3
        path: 3.9.3/dragen-umi__3.9.3.cwl
        md5sum: a9e764f4b6c304a0e3ea3a58caa59b24
    categories: []
  - name: bcftools-view
    path: bcftools-view
    versions:
      - name: 1.13.0
        path: 1.13.0/bcftools-view__1.13.0.cwl
        md5sum: 2ee45f43160d17d0ef7d7a1dddbe14dd
    categories: []
