workflows:
  - name: optitype-pipeline
    path: optitype-pipeline
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype-pipeline__1.3.5.cwl
        md5sum: 8a60ddcaa75b85884785de055320280f
    categories:
      - hla
  - name: get-hla-regions-bed
    path: get-hla-regions-bed
    versions:
      - name: 1.0.0
        path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
        md5sum: fde83608bc8d0624b260cc2fb9609420
    categories: []
  - name: dragen-germline-pipeline
    path: dragen-germline-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
        md5sum: 9c415babb9da86131c01d4e816d9ef67
      - name: 3.9.3
        path: 3.9.3/dragen-germline-pipeline__3.9.3.cwl
        md5sum: 481f644d4be0dfa1ecc9db76e38aed87
    categories:
      - dragen
  - name: dragen-qc-hla-pipeline
    path: dragen-qc-hla-pipeline
    versions:
      - name: 3.7.5--1.3.5
        path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
        md5sum: 5380314a8aec7e17de1f2be6ce95e75b
    categories: []
  - name: tso500-ctdna
    path: tso500-ctdna
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
        md5sum: c4829cfb415e023febda1b66a4c66ef0
    categories:
      - tso500
  - name: bcl-conversion
    path: bcl-conversion
    versions:
      - name: 3.7.5
        path: 3.7.5/bcl-conversion__3.7.5.cwl
        md5sum: 8a7e9463466cc66814227cf910f45b27
    categories: []
  - name: dragen-somatic-pipeline
    path: dragen-somatic-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic-pipeline__3.7.5.cwl
        md5sum: 90f8ccedf9d3566739425c519ed79d03
      - name: 3.9.3
        path: 3.9.3/dragen-somatic-pipeline__3.9.3.cwl
        md5sum: 1685a1b3b5802b4bb127df8cf63d5062
    categories:
      - dragen
      - variant-calling
  - name: dragen-transcriptome-pipeline
    path: dragen-transcriptome-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-transcriptome-pipeline__3.7.5.cwl
        md5sum: 4b835081d4c06aba76bb1a94e7ec46d1
      - name: 3.8.4
        path: 3.8.4/dragen-transcriptome-pipeline__3.8.4.cwl
        md5sum: d06c7d671f82027e581e0b67681a4d91
      - name: 3.9.3
        path: 3.9.3/dragen-transcriptome-pipeline__3.9.3.cwl
        md5sum: c15f336dcdb2c30f8252a1e65fc61f7f
    categories: []
  - name: dragen-alignment-pipeline
    path: dragen-alignment-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-alignment-pipeline__3.7.5.cwl
        md5sum: 7d1f53b5a952427be5dbcd1165795907
      - name: 3.9.3
        path: 3.9.3/dragen-alignment-pipeline__3.9.3.cwl
        md5sum: c7670e769139d2bfd103456f9e08e482
    categories:
      - alignment
      - dragen
  - name: dragen-wgs-qc-pipeline
    path: dragen-wgs-qc-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-wgs-qc-pipeline__3.7.5.cwl
        md5sum: e8a5f7e0631cb9d14303f56d67e408d7
      - name: 3.9.3
        path: 3.9.3/dragen-wgs-qc-pipeline__3.9.3.cwl
        md5sum: fb7e3d52e6e62a68c052531938ba677f
    categories:
      - dragen
  - name: tso500-ctdna-post-processing-pipeline
    path: tso500-ctdna-post-processing-pipeline
    versions:
      - name: 1.0.0
        path: 1.0.0/tso500-ctdna-post-processing-pipeline__1.0.0.cwl
        md5sum: 132cba4d9d45fab4344ca0bc56c11456
    categories:
      - tso500
  - name: umccrise-pipeline
    path: umccrise-pipeline
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/umccrise-pipeline__1.2.1--0.cwl
        md5sum: 6100f32cc0c1ecf82da6ea0da96f8622
      - name: 1.2.2--0
        path: 1.2.2--0/umccrise-pipeline__1.2.2--0.cwl
        md5sum: 54fb347935cbbf36c5a36b7e4df6240d
    categories: []
  - name: tso500-ctdna-with-post-processing-pipeline
    path: tso500-ctdna-with-post-processing-pipeline
    versions:
      - name: 1.1.0--1.0.0
        path: 1.1.0--1.0.0/tso500-ctdna-with-post-processing-pipeline__1.1.0--1.0.0.cwl
        md5sum: acf845c12be68021133f05444afbe80a
    categories:
      - tso500
  - name: umccrise-pipeline
    path: umccrise-pipeline
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/umccrise-pipeline__1.2.1--0.cwl
        md5sum: 6100f32cc0c1ecf82da6ea0da96f8622
      - name: 1.2.2--0
        path: 1.2.2--0/umccrise-pipeline__1.2.2--0.cwl
        md5sum: 54fb347935cbbf36c5a36b7e4df6240d
    categories: []
  - name: umccrise-with-dragen-germline-pipeline
    path: umccrise-with-dragen-germline-pipeline
    versions:
      - name: 2.0.0--3.9.3
        path: 2.0.0--3.9.3/umccrise-with-dragen-germline-pipeline__2.0.0--3.9.3.cwl
        md5sum: 7d5e5ae51a3dad19f1ef000702c56522
      - name: 2.0.1--3.9.3
        path: 2.0.1--3.9.3/umccrise-with-dragen-germline-pipeline__2.0.1--3.9.3.cwl
        md5sum: eea6638c5b341faac5c6ff58ba0499d3
      - name: 2.0.2--3.9.3
        path: 2.0.2--3.9.3/umccrise-with-dragen-germline-pipeline__2.0.2--3.9.3.cwl
        md5sum: a187951b8d0ee2cb2a0e56f1fa49a608
    categories: []
  - name: ghif-qc
    path: ghif-qc
    versions:
      - name: 1.0.0
        path: 1.0.0/ghif-qc__1.0.0.cwl
        md5sum: cc6a47a96c3d1b0e58a149c1f9610f28
      - name: 1.0.1
        path: 1.0.1/ghif-qc__1.0.1.cwl
        md5sum: ddb44d838b99afb76eb4d433a54d60de
    categories: []
  - name: dragen-pon-qc
    path: dragen-pon-qc
    versions:
      - name: 3.9.3
        path: 3.9.3/dragen-pon-qc__3.9.3.cwl
        md5sum: 266daf3307662965d0450a35c29f394e
    categories: []
